CREATE DATABASE IF NOT EXISTS BD_ESTOQUE_MERCADO;
USE BD_ESTOQUE_MERCADO;

CREATE TABLE IF NOT EXISTS  CATEGORIA (

	ID INT PRIMARY KEY,
    TIPO VARCHAR(50),
    NOME VARCHAR(255)
    
);

CREATE TABLE IF NOT EXISTS FORNECEDOR(

	CPF_CNPJ VARCHAR(14) PRIMARY KEY,
    EMAIL VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(9) NOT NULL,
    NOME VARCHAR(255) NOT NULL

);

CREATE TABLE IF NOT EXISTS PRODUTO(

	ID INT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    PRECO INT NOT NULL, 
    DESCRICAO VARCHAR (1000),
    FK_CATEGORIA_ID INT,
    FOREIGN KEY (FK_CATEGORIA_ID) REFERENCES CATEGORIA(ID)

);


CREATE TABLE IF NOT EXISTS PRODUTO_FORNECEDOR(

	FK_PRODUTO_ID INT,
    FK_FORNECEDOR_CPF_CNPJ VARCHAR(14),
    FOREIGN KEY (FK_PRODUTO_ID) REFERENCES PRODUTO(ID),
    FOREIGN KEY (FK_FORNECEDOR_CPF_CNPJ) REFERENCES FORNECEDOR(CPF_CNPJ)

);