CREATE DATABASE IF NOT EXISTS BD_MUSICA;
USE BD_MUSICA;

CREATE TABLE IF NOT EXISTS ARTISTA(

	CPF VARCHAR(11) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(9) NOT NULL

);

CREATE TABLE IF NOT EXISTS GENERO(

	ID INT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    TIPO_BATIDA VARCHAR(50) NOT NULL

);

CREATE TABLE IF NOT EXISTS  ALBUM(

	ID INT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    DATA_LANCAMENTO DATE,
	FK_ARTISTA_CPF VARCHAR(11),
    FOREIGN KEY (FK_ARTISTA_CPF) REFERENCES ARTISTA(CPF)
    
);